// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyByatIZW_CCIeTvgG7S9yGFwIG_bcE-oPU",
    authDomain: "capston-5713f.firebaseapp.com",
    databaseURL: "https://capston-5713f-default-rtdb.firebaseio.com",
    projectId: "capston-5713f",
    storageBucket: "capston-5713f.appspot.com",
    messagingSenderId: "582630173242",
    appId: "1:582630173242:web:c9ca631ddcd2d614d1e303",
    measurementId: "G-4SHWB0KZT2"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd1DQUIFOuN3UPJdWBVfvAJ9ngugnZ0FE',
    appId: '1:582630173242:android:809d8fa60259f022d1e303',
    messagingSenderId: '582630173242',
    projectId: 'capston-5713f',
    storageBucket: 'capston-5713f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpLjJL27hF41xuXf6cS62mtd8vfA9_uc',
    appId: '1:582630173242:ios:83a6fc1a2052a607d1e303',
    messagingSenderId: '582630173242',
    projectId: 'capston-5713f',
    storageBucket: 'capston-5713f.appspot.com',
    iosBundleId: 'com.example.capston',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpLjJL27hF41xuXf6cS62mtd8vfA9_uc',
    appId: '1:582630173242:ios:83a6fc1a2052a607d1e303',
    messagingSenderId: '582630173242',
    projectId: 'capston-5713f',
    storageBucket: 'capston-5713f.appspot.com',
    iosBundleId: 'com.example.capston',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByatIZW_CCIeTvgG7S9yGFwIG_bcE-oPU',
    appId: '1:582630173242:web:faf3f036a6c6e1fbd1e303',
    messagingSenderId: '582630173242',
    projectId: 'capston-5713f',
    authDomain: 'capston-5713f.firebaseapp.com',
    storageBucket: 'capston-5713f.appspot.com',
    measurementId: 'G-PBNW83XHMG',
  );
}
